// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _2019121885801 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2019121885801));
        
        string IMigrationMetadata.Id
        {
            get { return "201912180126108_2019121885801"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
