// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _2019121885802 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2019121885802));
        
        string IMigrationMetadata.Id
        {
            get { return "201912180126537_2019121885802"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
