// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201912250823139_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
